try:
	1/0
except Exception as e:
	catched = e
